---
title: "Problema1-Checkpoint4"
author: "Arthur Lustosa"
date: "26-07-2016"
output: html_document
---

```{r}
#dependencias = c("dplyr", "ggplot2", "GGally", "readr", "plotly")
#devtools::install_github("ropensci/plotly")
#install.packages(dependencias)

library(dplyr, warn.conflicts = FALSE)
library(ggplot2)
library(plotly)

```

### Discplina de Análise de Dados 1- Ciência da Computação UFCG - 2016.1

```{r}
dados <- read.csv("dados/ano-atual.csv")
```



```{r}
deputados.pb <- dados %>%
  filter(sgUF == "PB") %>%
  select(txNomeParlamentar, sgPartido) %>%
  distinct()

#filtrando os deputados da paraiba
deputados.pb <- c("AGUINALDO RIBEIRO", "BENJAMIN MARANHÃO", "DAMIÃO FELICIANO", "EFRAIM FILHO", "HUGO MOTTA", "LUIZ COUTO", "MANOEL JUNIOR", "MARCONDES GADELHA", "PEDRO CUNHA LIMA", "RÔMULO GOUVEIA", "VENEZIANO VITAL DO RÊGO", "WELLINGTON ROBERTO", "WILSON FILHO")

fornecedores.deputados.pb <- dados %>%
  filter(txNomeParlamentar %in% deputados.pb ) %>%
  select(txNomeParlamentar, txtCNPJCPF, txtFornecedor, txtDescricao, vlrDocumento) %>%
  mutate(txtCNPJCPF = as.factor(txtCNPJCPF)) %>%
  group_by(txNomeParlamentar, txtCNPJCPF, txtFornecedor, txtDescricao) %>%
  summarise(valor.total = sum(vlrDocumento)) %>%
  ungroup()

fornecedores.deputados.pb <- fornecedores.deputados.pb %>%
  mutate(txtDescricao = as.character(txtDescricao)) %>%
  mutate(txtDescricao = ifelse(valor.total < 1000, "OUTROS", txtDescricao))

fornecedores.hugo.motta <- fornecedores.hugo.motta %>%
  mutate(txtFornecedor = as.character(txtFornecedor)) %>%
  mutate(txtFornecedor = ifelse(valor.total < 1000, "OUTROS", txtFornecedor))

fornecedores.deputados.pb <- fornecedores.deputados.pb %>%
  group_by(txtFornecedor) %>%
  summarise(valor.total = sum(valor.total))

fornecedores.deputados.pb <- fornecedores.deputados.pb[ order(-fornecedores.deputados.pb[,5]), ]

b <- ggplot(data=fornecedores.deputados.pb, aes(x=reorder(txtFornecedor, valor.total), y=valor.total, fill = txtDescricao, size = valor.total)) + 
  geom_bar(stat="identity") +
  facet_wrap(~txNomeParlamentar, scales = "free") +
  labs(title="Fornecedores Deputados Paraibanos", x="Fornecedor", y="Total")

b

```

```{r, autosize=F, width=900, height=600}

fornecedores.hugo.motta <- fornecedores.deputados.pb %>%
  filter(txNomeParlamentar == "HUGO MOTTA") %>%
  select(txtCNPJCPF, txtFornecedor, txtDescricao, valor.total) %>%
  group_by(txtCNPJCPF, txtFornecedor, txtDescricao) %>%
  summarise(valor.total = sum(valor.total)) %>% 
  ungroup()

fornecedores.hugo.motta <- fornecedores.hugo.motta[ order(-fornecedores.hugo.motta[,4]), ]

fornecedores.hugo.motta <- fornecedores.hugo.motta %>%
  mutate(txtFornecedor = as.character(txtFornecedor)) %>%
  mutate(txtFornecedor = ifelse(valor.total < 1000, "OUTROS", txtFornecedor))

fornecedores.hugo.motta <- fornecedores.hugo.motta %>%
  mutate(txtDescricao = as.character(txtDescricao)) %>%
  mutate(txtDescricao = ifelse(valor.total < 1000, "OUTROS", txtDescricao))

fornecedores.hugo.motta <- fornecedores.hugo.motta[ order(-fornecedores.hugo.motta[,4]), ]


ggplot(data=fornecedores.hugo.motta, aes(x=reorder(txtFornecedor, valor.total), y=valor.total)) + 
  geom_bar(stat="identity") +
  coord_flip() +
  labs(title="Fornecedores Deputado Hugo Motta", x="Fornecedor", y="Total")

d <- ggplot(data=fornecedores.hugo.motta, aes(x=reorder(txtFornecedor, valor.total), y=valor.total, fill = txtDescricao, size = valor.total)) + 
  geom_bar(stat="identity") +
  coord_flip() +
  labs(title="Fornecedores Deputado Hugo Motta", x="Fornecedor", y="Total")

d

b <- ggplot(data=fornecedores.deputados.pb, aes(x=reorder(txtFornecedor, valor.total), y=valor.total, fill = txtDescricao, size = valor.total)) + 
  geom_bar(stat="identity") +
  facet_wrap(~txNomeParlamentar, scales = "free")
  coord_flip() +
  labs(title="Fornecedores Deputado Hugo Motta", x="Fornecedor", y="Total")

b

fornecedores.hugo.motta[-1,]

p <- plot_ly(fornecedores.hugo.motta[-1,], 
             x = valor.total, 
             y = txtFornecedor, 
             text = paste("Tipo ", txtDescricao),
             mode = "markers", 
             color = txtDescricao,
             size= valor.total)
p


```


```{r, autosize=F, width=900, height=600}

fornecedores.veneziano <- fornecedores.deputados.pb %>%
  filter(txNomeParlamentar == "VENEZIANO VITAL DO RÊGO") %>%
  select(txtCNPJCPF, txtFornecedor, txtDescricao, valor.total) %>%
  group_by(txtCNPJCPF, txtFornecedor, txtDescricao) %>%
  summarise(valor.total = sum(valor.total)) %>% 
  ungroup()

fornecedores.veneziano <- fornecedores.veneziano[ order(-fornecedores.veneziano[,4]), ]

fornecedores.veneziano <- fornecedores.veneziano %>%
  mutate(txtFornecedor = as.character(txtFornecedor)) %>%
  mutate(txtFornecedor = ifelse(valor.total < 1000, "OUTROS", txtFornecedor))

fornecedores.veneziano <- fornecedores.veneziano %>%
  mutate(txtDescricao = as.character(txtDescricao)) %>%
  mutate(txtDescricao = ifelse(valor.total < 1000, "OUTROS", txtDescricao))

fornecedores.veneziano <- fornecedores.veneziano[ order(-fornecedores.veneziano[,4]), ]


ggplot(data=fornecedores.hugo.motta, aes(x=reorder(txtFornecedor, valor.total), y=valor.total)) + 
  geom_bar(stat="identity") +
  coord_flip() +
  labs(title="Fornecedores Deputado Hugo Motta", x="Fornecedor", y="Total")

d <- ggplot(data=fornecedores.hugo.motta, aes(x=reorder(txtFornecedor, valor.total), y=valor.total, fill = txtDescricao, size = valor.total)) + 
  geom_bar(stat="identity") +
  coord_flip() +
  labs(title="Fornecedores Deputado Hugo Motta", x="Fornecedor", y="Total")

d



p <- plot_ly(fornecedores.veneziano, 
             x = valor.total, 
             y = txtFornecedor, 
             text = paste("Tipo ", txtDescricao),
             mode = "markers", 
             color = txtDescricao)
p

fornecedores.dep.pb <- function(nome.deputado) {
  
  fornecedores.veneziano <- fornecedores.deputados.pb %>%
  filter(txNomeParlamentar == nome.deputado) %>%
  select(txtCNPJCPF, txtFornecedor, txtDescricao, valor.total) %>%
  group_by(txtCNPJCPF, txtFornecedor, txtDescricao) %>%
  summarise(valor.total = sum(valor.total)) %>% 
  ungroup()

fornecedores.veneziano <- fornecedores.veneziano[ order(-fornecedores.veneziano[,4]), ]

fornecedores.veneziano <- fornecedores.veneziano %>%
  mutate(txtFornecedor = as.character(txtFornecedor)) %>%
  mutate(txtFornecedor = ifelse(valor.total < 1000, "OUTROS", txtFornecedor))

fornecedores.veneziano <- fornecedores.veneziano %>%
  mutate(txtDescricao = as.character(txtDescricao)) %>%
  mutate(txtDescricao = ifelse(valor.total < 1000, "OUTROS", txtDescricao))

fornecedores.veneziano <- fornecedores.veneziano[ order(-fornecedores.veneziano[,4]), ]

p <- plot_ly(fornecedores.veneziano, 
             x = valor.total, 
             y = txtFornecedor, 
             text = paste("Tipo ", txtDescricao),
             mode = "markers", 
             color = txtDescricao)
p
  
}

fornecedores.dep.pb("DAMIÃO FELICIANO")


```
