---
title: "Problema1-Checkpoint4"
author: "Arthur Lustosa"
date: "13-07-2016"
output: html_document
---

```{r}
#dependencias = c("dplyr", "ggplot2", "GGally", "readr", "plotly")
#devtools::install_github("ropensci/plotly")
#install.packages(dependencias)

library(dplyr, warn.conflicts = FALSE)
library(ggplot2)
library(plotly)


```


```{r}
dados <- read.csv("dados/ano-atual.csv")
```


```{r}
#(Pergunta 1) Dando um foco no nosso estado (Paraíba), quais fornecedores mais se destacam aqui no nosso estado, essas empresas são realmente daqui? Se sim, qual a relação entre nossos deputados e esses fornecedores?
#(Pergunta 2) Analisando o gasto dos deputados com passagens aéreas, é esperado que esses gastos tenha uma correlação com o estado de origem do deputado, isso realmente existe? Existem outliers nesses gastos, se sim, como podemos entendê-los?


```


```{r}
deputados.pb <- dados %>%
  filter(sgUF == "PB") %>%
  select(txNomeParlamentar, sgPartido) %>%
  distinct()

#filtrando os deputados da paraiba
deputados.pb <- c("AGUINALDO RIBEIRO", "BENJAMIN MARANHÃO", "DAMIÃO FELICIANO", "EFRAIM FILHO", "HUGO MOTTA", "LUIZ COUTO", "MANOEL JUNIOR", "MARCONDES GADELHA", "PEDRO CUNHA LIMA", "RÔMULO GOUVEIA", "VENEZIANO VITAL DO RÊGO", "WELLINGTON ROBERTO", "WILSON FILHO")

fornecedores.deputados.pb <- dados %>%
  filter(txNomeParlamentar %in% deputados.pb ) %>%
  select(txNomeParlamentar, txtCNPJCPF, txtFornecedor, txtDescricao, vlrDocumento) %>%
  mutate(txtCNPJCPF = as.factor(txtCNPJCPF)) %>%
  group_by(txNomeParlamentar, txtCNPJCPF, txtFornecedor, txtDescricao) %>%
  summarise(valor.total = sum(vlrDocumento))

```

```{r, autosize=F, width=900, height=600}

fornecedores.hugo.motta <- fornecedores.deputados.pb %>%
  filter(txNomeParlamentar == "HUGO MOTTA") %>%
  select(txtCNPJCPF, txtFornecedor, txtDescricao, valor.total) %>%
  group_by(txtFornecedor, txtDescricao) %>%
  summarise(valor.total = sum(valor.total))
  
  

ggplot(data=fornecedores.hugo.motta, aes(x=reorder(txtFornecedor, valor.total), y=valor.total)) + 
  geom_bar(stat="identity") +
  coord_flip() +
  labs(title="Fornecedores Deputado Hugo Motta", x="Fornecedor", y="Total")


plot_ly(data = fornecedores.hugo.motta, x = valor.total, y = txtFornecedor, mode = "markers", color = txtDescricao)

```

```{r, autosize=F, fig.width = 12, fig.height = 7}
cia.aereas <- c("Cia Aérea - TAM", "Avianca", "Azul Linhas Aéreas", "Cia Aérea - AVIANCA", "Cia Aérea - AZUL","Cia Aérea - GOL", "GOL - LINHAS AÉREAS INTELIGENTES", "GOL - LINHAS AÉREAS S/A", "Cia Aérea - TAM", "TAM LINAS AÉREAS S.A", "Tam Linhas Aéreas")

gastos.passagens.aereas <- fornecedores.deputados.pb %>%
  filter(txtFornecedor %in% cia.aereas) %>%
  group_by(txNomeParlamentar) %>%
  summarise(valor.total = sum(valor.total))



ranking.gastos <- plot_ly(gastos.passagens.aereas,
  x = reorder(txNomeParlamentar, valor.total),
  y = valor.total,
  name = "Gastos Passagens Aéreas",
  type = "bar")

ranking.gastos

```
O ranking acima nos mostra o valor total dos gastos dos deputados com passagens aéreas.


```{r, autosize=F, fig.width = 12, fig.height = 7}

```
Companhias aéreas que mais lucram com os deputados paraibanos.

```{r, autosize=F, fig.width = 12, fig.height = 7}

gastos.passagens.aereas.empresas <- fornecedores.deputados.pb %>%
  filter(txtFornecedor %in% cia.aereas) %>%
  group_by(txNomeParlamentar, txtFornecedor) %>%
  summarise(valor.total = sum(valor.total))

cia.tam <- c("Cia Aérea - TAM", "TAM LINAS AÉREAS S.A", "Tam Linhas Aéreas")
tam <- gastos.passagens.aereas.empresas %>%
  filter(txtFornecedor %in% cia.tam)

p <- plot_ly(tam,
  x = txNomeParlamentar,
  y = reorder(valor.total, valor.total),
  name = "Tam",
  type = "bar")

cia.avianca <- c("Avianca","Cia Aérea - AVIANCA")
avianca <- gastos.passagens.aereas.empresas %>%
  filter(txtFornecedor %in% cia.avianca)

p2 <- add_trace(
  avianca,
  x = txNomeParlamentar,
  y = valor.total,
  name = "Avianca",
  type = "bar")

cia.azul <- c("Azul Linhas Aéreas","Cia Aérea - AZUL")
azul <- gastos.passagens.aereas.empresas %>%
  filter(txtFornecedor %in% cia.azul)

p3 <- add_trace(
  azul,
  x = txNomeParlamentar,
  y = valor.total,
  name = "Azul",
  type = "bar")

cia.gol <- c("Cia Aérea - GOL", "GOL - LINHAS AÉREAS INTELIGENTES", "GOL - LINHAS AÉREAS S/A")
gol <- gastos.passagens.aereas.empresas %>%
  filter(txtFornecedor %in% cia.gol)

p4 <- add_trace(
  gol,
  x = txNomeParlamentar,
  y = valor.total,
  name = "Gol",
  type = "bar")

p5 <- layout(p4, barmode = "stack")
  

p5

```
No gráfico acima temos a distribuição dos gastos dos deputados paraibanos de acordo com as companhias aéreas. 

```{r, autosize=F, fig.width = 12, fig.height = 7}

```
