---
title: "problema3-cp1"
output: html_document
---



```{r setup, include=FALSE}
require(ggplot2, quietly = TRUE)
require(GGally, quietly = TRUE)
require(reshape2, quietly = TRUE)
require(dplyr, quietly = TRUE)
library(ggfortify)
library(cluster)
library(ggdendro)

```

```{r setup, include=FALSE}

detalhes_emendas <- read.csv("dados/emendas_detalhes_parlamentar.csv")
emendas <- read.csv("dados/emendas_area_parlamentar.csv")

``` 



```{r}



``` 

```{r}
#hierarchical

#row.names(emendas)  = emendas$NOME_PARLAMENTAR
dists = dist(emendas[,2:18], method = "euclidean")
hc = hclust(dists, method = "ward.D")

plot(hc, cex = .3)
plot(hc, hang = -1)
rect.hclust(hc, k=5)


```

```{r}
#PCA
emendas2 <- log(emendas[,2:18])
df <- emendas[,2:18]
autoplot(prcomp(df))

autoplot(prcomp(df), data = emendas, label = TRUE, loadings = TRUE, frame = TRUE)



```


```{r}
#k-means

km <- kmeans(emendas[,2:18], centers=5, nstart=10)
km

autoplot(km, data = emendas[,2:18])

autoplot(km, data = emendas[,2:18], frame = TRUE)


```



