---
title: "prob4-cp1"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
movie = read.csv("dados/ml-latest-small/movies.csv", stringsAsFactors = F)
rating = read.csv("dados/ml-latest-small/ratings.csv", stringsAsFactors = F)
tags = read.csv("dados/ml-latest-small/tags.csv", stringsAsFactors = F)
links = read.csv("dados/ml-latest-small/links.csv", stringsAsFactors = F)
```

## Conhecendo os Dados
Vamos dar uma olhada nos dados fornecidos para essa análise. Os dados são referentes a avaliações de filmes, feitas por usuários, coletadas aleatóriamente pelo Movielens ["https://movielens.org/"] disponibilizados no site ["http://grouplens.org/datasets/movielens/latest/"]. O conjunto de dados escolhido é o de menor volume, cerca de 10.000 filmes com 100.000 avaliações.

```{r cars}
count.genres <- movie %>%
  select(genres) %>%
  distinct()

genres <- c("Action", "Adventure", "Animation", "Children's", "Comedy", "Crime", "Documentary", "Drama", "Fantasy", "Film-Noir", "Horror", "Musical", "Mystery", "Romance", "Sci-Fi", "Thriller", "War", "Western", "(no genres listed)")

```

## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}

```

